### ISSUE TITLE
OOM on RTX 5090

### ISSUE THREAD

**Issue by Marcophono2** [stepfun-ai/Step1X-Edit#43]
Hello!
I have replaced the model with your step1x-edit-i1258-FP8.safetensors and tried to start it with `python gradio_app.py` . Unfortunatelly it ends with a OOM error for VRAM. Before launching the script the VRAM is only reserved with 0.5 GB from 32 GB. As far as I understand your statements, processing images with 512x512 should be able (with a bit of good luck may be 768x768) but I simple fail with launching the gradio UI.
Any ideas what I could have done wrong? Of course I not only replaced the model, I also adjusted the path to it in gradio_app.py .

Best regards
Marc

**Comment by Zzlongjuanfeng** [comment]
@Marcophono2 Hi, we have updated the `gradio_app.py`, and it works like `inference.py` now. The gradio script has been verified to be usable on a local (4090) GPU. For more details, please refer to #40.
